#!/usr/bin/env bash
# Make a new reminder via terminal script
# args: remind <title> <date> <time>

osascript - "$1" <<END
on run argv
    tell application "Reminders"
        if not (exists (first reminder whose name is (item 1 of argv))) then
            make new reminder with properties {name:item 1 of argv}
        end if
    end tell
end run
END
